### ISSUE TITLE
Parsing of FEV obtained from nucleotide matches is broken

### ISSUE THREAD

**Issue by asl** [ababaian/palmid#20]
Here is an example hash: https://serratus.io/palmid?hash=cb8c52eaed12dbb84c8959f40314ee1dbeead975

It seems that `read.fev` and `fev2df` does not support FEVs obtained from nucleotide matches as two extra fields `xlat` and `frame` are present in FEV:

```
score=54.3	query=NODE_1_length_7593_cov_35.116356	gene=RdRP	confidence=high	comments=high-PSSM-score.reward-DDGGDD.good-segment-length.	order=ABC	qlen=7593	xlat=yes	pp_start=5355	pp_end=5639	pp_length=285	frame=+3	pssm_total_score=44.3	pssm_min_score=10.8	order=ABC	v1_length=44	v2_length=17	group=Kitrino	super=DDGGDD	motifs=TANDVTGWDTGVxxxSGDPYTWLANTLVNxxxFSGDDFIA
```

As a result nucleotide sequences could not be analyzed w/o prior explicit translation

Tagging @ababaian @hannahhanle

**Comment by ababaian** [comment]
This error is now resolved in v0.0.6
