### ISSUE TITLE
Error in FUN(newX[, i], ...) : .fev input has an unrecognized .fev value

### ISSUE THREAD

**Issue by biofuture** [ababaian/palmid#8]
Hello, I got this error while running the docker version under ubuntu 18.04 version.   Can you help me to find out why?  

Quitting from lines 65-147 (palmid.Rmd) 
Error in FUN(newX[, i], ...) : .fev input has an unrecognized .fev value
Calls: <Anonymous> ... eval -> eval -> read.fev -> as.data.frame -> apply -> FUN

Execution halted

Thank you very much.

**Comment by ababaian** [comment]
Can you link the output of the `.fev` file and I can take a look at what the unrecognized value is?

**Comment by ababaian** [comment]
Is this resolved?

**Comment by biofuture** [comment]
[rdrp-palmid-total.fev.txt](https://github.com/ababaian/palmid/files/8508784/rdrp-palmid-total.fev.txt)

Please check the fev  file, the problem is not solved yet.

**Comment by ababaian** [comment]
Merging issue with #9 as these appear to be the same problem.
