### ISSUE TITLE
Alert: abnormal wrong output for the alignment result the .pro file? 

### ISSUE THREAD

**Issue by biofuture** [ababaian/palmid#9]
Hello, 

I have run the palmid dockerversion for 196 sequences identified by palmscan to do the taxa annotation. 

The alignment output, only output alignment for 15 sequences, and some of them doing repeating alignment and report different u_taxa IDs, I am wondering whether there is any bugs in the pipeline while doing the alignment of the sequence to palmdb, 

For example, the contig k141_529409 report alignment hits for 3480 times in the output file. 

 Below is the output of the palmid alignment, 
 cut -f 1  rdrpDNA/rdrp-palmid-total.pro  | sort | uniq -c
   1950 k141_1046322
      1 k141_1123094
      1 k141_1208951
      1 k141_1300038
      1 k141_1330838
   2319 k141_1348444
      1 k141_152892
      1 k141_1535510
      4 k141_1641097
      1 k141_208180
      1 k141_474737
   3480 k141_529409
      1 k141_569638
      1 k141_673165
   2352 k141_702219

**Comment by ababaian** [comment]
I don't fully understand what the issue is here. It looks like `k141_529409` has 3480 hits in the pipeline. Pro files report the following fields (DIAMOND output), so you're looking at query sequence, which is the input. The `sseqid` will be the matching palmprints (`uNNNNN`) and those will be unique for each query-sequence input.

```
  -f 6 qseqid  qstart qend qlen \
       sseqid  sstart send slen \
       pident evalue cigar \
       full_sseq
```

`palmID` does not report a single "best" hit, it will return the top 500 hits in the database and create a meta-annotation of the input. There are far more unknown viruses than known viruses, so the idea is to use the few knowns to infer what an input is "like". Strictly speaking this is not a taxonomy program.

**Comment by ababaian** [comment]
Is this resolved?

**Comment by biofuture** [comment]
Thanks,  I have 190 contigs that detected by palmscan that has RdRps.  Then I put them into palmID for taxonomy. It only reports results for only 15 contigs, and as you can see in the output, one contigs has output many results, which are located in different sections in the output file.  It seem that these contigs are put into the DIAMOND alignment for many times and get different alignment output.  I have no idea what's happening here.

**Comment by biofuture** [comment]
> Is this resolved?

Not solved.

**Comment by ababaian** [comment]
It looks like 165 of the hits you give are for `gene=RT` (Reverse Transcriptase) and not RdRP. It is correct that `palmID` will not report RT hits, RT hits are used as a way of depleting false-positives, neither palmscan nor palmID is currently set-up for classifying RT.

`palmscan` should not be reporting RT hits when used in the standard workflows, please run the `palmID` container without modification and report the output, from the 31 remaining hits none are duplicate contigs.

**Comment by ababaian** [comment]
@biofuture is this resolved?

**Comment by biofuture** [comment]
Not yet, we run the program again and get the same number of RDRPs that including all the ones that you regard as RTs. 

The command we use to find the RDRP

palmscan -search_pp  input.fa -rt -rdrp -ppout pp.fa -ppout_nt pp_nt.fa -report po.txt -fevout pp.fev -threads 16

Thank you very much.

**Comment by biofuture** [comment]
>

**Comment by biofuture** [comment]
@ababaian   May I ask how did you find that the 165 of them are RT rather than RdRp detected by palmscan?  We need to confirm the accuracy of the detected RNA viruses.

**Comment by ababaian** [comment]
In the `.fev` files the `gene=RT` for the RT hits, or the `gene=RdRP` for the RdRP hits. You can run `palmscan`.

**Comment by biofuture** [comment]
Thanks I will have a check
